apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-postgres-config
  namespace: "oauth"
  labels:
    app: oauth-postgres
data:
  POSTGRES_DB: oauth
  POSTGRES_USER: postgre_test_user
  POSTGRES_PASSWORD: postgre_test_pass
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: oauth-postgres-volume
  namespace: "oauth"
  labels:
    type: local
    app: oauth-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oauth-postgres-pv-claim
  namespace: "oauth"
  labels:
    app: oauth-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oauth-postgres
  namespace: "oauth"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth-postgres
    spec:
      containers:
        - name: oauth-postgres
          image: postgres:11
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: oauth-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
              subPath: oauth
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: oauth-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-postgres
  namespace: "oauth"
  labels:
    app: oauth-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: oauth-postgres
